trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  environment: 'prod'

stages:

  - stage: TerraformPlan
    displayName: "Terraform Init and Plan"
    jobs:
      - job: Plan
        displayName: "Terraform Plan"
        steps:
          - task: AzureCLI@2
            displayName: "Terraform Init & Plan"
            inputs:
              azureSubscription: 'TerraformServiceConnection' 
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Initializing Terraform..."
                terraform init -backend-config="key=prod.terraform.tfstate"

                echo "Running Terraform Plan..."
                terraform plan \
                  -var "subscription_id=$(ARM_SUBSCRIPTION_ID)" \
                  -var "client_id=$(ARM_CLIENT_ID)" \
                  -var "client_secret=$(ARM_CLIENT_SECRET)" \
                  -var "tenant_id=$(ARM_TENANT_ID)" \
                  -out=tfplan
            env:
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID: $(ARM_TENANT_ID)

  - stage: TerraformApply
    displayName: "Terraform Apply"
    dependsOn: TerraformPlan
    condition: succeeded()
    jobs:
      - deployment: Apply
        displayName: "Terraform Apply with Approval"
        environment: 'Production'  # ✅ Requires pre-created environment with approval
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: "Terraform Apply"
                  inputs:
                    azureSubscription: 'TerraformServiceConnection'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      echo "Applying Terraform Plan..."
                      terraform apply -auto-approve tfplan
                  env:
                    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
                    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
                    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
                    ARM_TENANT_ID: $(ARM_TENANT_ID)
