trigger: none

pool:
  vmImage: ubuntu-latest

stages:
# ----------------------------------
# Stage 1: Terraform Init
# ----------------------------------
- stage: Init
  displayName: "Terraform Init"
  jobs:
  - job: InitJob
    displayName: "Initialize Terraform"
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'TerraformServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(Build.SourcesDirectory)'
        inlineScript: |
          terraform init -upgrade

    - publish: $(Build.SourcesDirectory)/.terraform.lock.hcl
      artifact: terraform-lock

# ----------------------------------
# Stage 2: Terraform Plan
# ----------------------------------
- stage: Plan
  displayName: "Terraform Plan"
  dependsOn: Init
  condition: succeeded()
  jobs:
  - deployment: PlanJob
    environment: manual-approval-plan
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - download: current
            artifact: terraform-lock

          - script: |
              mv $(Pipeline.Workspace)/terraform-lock/.terraform.lock.hcl $(Build.SourcesDirectory)
            displayName: "Move lock file to working dir"

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'TerraformServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(Build.SourcesDirectory)'
              inlineScript: |
                terraform plan -var-file="terraform.tfvars"

# ----------------------------------
# Stage 3: Terraform Apply
# ----------------------------------
- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: ApplyJob
    environment: manual-approval-apply
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - download: current
            artifact: terraform-lock

          - script: |
              mv $(Pipeline.Workspace)/terraform-lock/.terraform.lock.hcl $(Build.SourcesDirectory)
            displayName: "Move lock file to working dir"

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'TerraformServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(Build.SourcesDirectory)'
              inlineScript: |
                terraform apply -auto-approve -var-file="terraform.tfvars"
