trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: 'prod'

stages:
  - stage: Terraform
    displayName: 'Terraform Apply Stage'
    jobs:
      - job: TerraformJob
        displayName: 'Terraform Plan and Apply'
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Terraform Init, Plan, Apply'
            inputs:
              azureSubscription: 'TerraformServiceConnection'  # ⚠️ Replace this with your actual service connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Initializing Terraform"
                terraform init -input=false -backend-config="key=${{ variables.environment }}.terraform.tfstate"

                echo "Planning Terraform"
                terraform plan -input=false -var-file="terraform.tfvars"

                echo "Applying Terraform"
                terraform apply -auto-approve -input=false -var-file="terraform.tfvars"
