trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Init
  displayName: "Terraform Init"
  jobs:
  - job: InitJob
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-aks
          terraform init

- stage: Validate
  displayName: "Terraform Validate"
  dependsOn: Init
  condition: succeeded()
  environment: manual-approval-validate
  jobs:
  - job: ValidateJob
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-aks
          terraform validate

- stage: Plan
  displayName: "Terraform Plan"
  dependsOn: Validate
  condition: succeeded()
  environment: manual-approval-plan
  jobs:
  - job: PlanJob
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-aks
          terraform plan -var-file="terraform.tfvars"

- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Plan
  condition: succeeded()
  environment: manual-approval-apply
  jobs:
  - job: ApplyJob
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-aks
          terraform apply -auto-approve -var-file="terraform.tfvars"
