trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.6.6'

stages:
# Stage 1: Terraform Init and Plan
- stage: TerraformPlan
  displayName: "Terraform Plan"
  jobs:
  - job: Plan
    displayName: "Run terraform plan"
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: $(terraformVersion)

    - task: AzureCLI@2
      displayName: "Terraform Init and Plan"
      inputs:
        azureSubscription: 'TerraformServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(Build.SourcesDirectory)'
        inlineScript: |
          terraform init -input=false
          terraform plan -input=false -var-file="terraform.tfvars"

# Stage 2: Manual Approval + Apply
- stage: TerraformApply
  displayName: "Terraform Apply"
  dependsOn: TerraformPlan
  condition: succeeded()
  jobs:
  - deployment: Apply
    displayName: "Manual Approval and Apply"
    environment: approval-environment   # ⚠️ Must be configured in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(terraformVersion)

          - task: AzureCLI@2
            displayName: "Terraform Init and Apply"
            inputs:
              azureSubscription: 'TerraformServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(Build.SourcesDirectory)'
              inlineScript: |
                terraform init -input=false
                terraform apply -input=false -auto-approve -var-file="terraform.tfvars"
