stages:
  - stage: TerraformInitPlan
    jobs:
      - job: InitAndPlan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'TerraformServiceConnection'
              backendAzureRmResourceGroupName: 'Az-104'
              backendAzureRmStorageAccountName: 'glowsatf'
              backendAzureRmContainerName: 'sacont'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'TerraformServiceConnection'

  - stage: TerraformApply
    displayName: 'Manual Approval Before Apply'
    dependsOn: TerraformInitPlan
    condition: succeeded()
    approval:
      # This doesn't go in YAML; see the note below
    jobs:
      - job: Apply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'TerraformServiceConnection'