trigger: none

resources:
  repositories:
    - repository: self
      type: github
      name: github.com/SHIVRAJPATIL123/glow-aks-deploy
      ref: main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Init
  displayName: "Terraform Init"
  jobs:
  - job: InitJob
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'TerraformServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(Build.SourcesDirectory)'
        inlineScript: |
          terraform init -upgrade


- stage: Plan
  displayName: "Terraform Plan"
  dependsOn: Init
  condition: succeeded()
  jobs:
  - deployment: PlanJob
    environment: manual-approval-plan
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'TerraformServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(Build.SourcesDirectory)'
              inlineScript: |
                terraform plan -var-file="terraform.tfvars"

- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: ApplyJob
    environment: manual-approval-apply
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'TerraformServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(Build.SourcesDirectory)'
              inlineScript: |
                terraform apply -auto-approve -var-file="terraform.tfvars"
