trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.6.6'

stages:
# ----------------------
# Stage 1: Terraform Plan
# ----------------------
- stage: TerraformPlan
  displayName: "Terraform Plan"
  jobs:
  - job: Plan
    displayName: "Run terraform plan"
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: $(terraformVersion)

    - task: AzureCLI@2
      displayName: "Terraform Init and Plan"
      inputs:
        azureSubscription: 'TerraformServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(Build.SourcesDirectory)'
        inlineScript: |
          terraform init -input=false
          terraform plan -input=false -var-file="terraform.tfvars"

# ----------------------
# Stage 2: Apply (Manual Approval)
# ----------------------
- stage: TerraformApply
  displayName: "Terraform Apply"
  dependsOn: TerraformPlan
  condition: succeeded()
  jobs:
  - deployment: Apply
    displayName: "Manual Approval and Apply"
    environment: approval-environment  # 💡 You must create this in Azure DevOps (with approvers)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(terraformVersion)

          - task: AzureCLI@2
            displayName: "Terraform Init and Apply"
            inputs:
              azureSubscription: 'TerraformServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(Build.SourcesDirectory)'
              inlineScript: |
                terraform init -input=false
                terraform apply -input=false -auto-approve -var-file="terraform.tfvars"

# ----------------------
# Stage 3: Destroy (Manual Trigger + Approval)
# ----------------------
- stage: TerraformDestroy
  displayName: "Terraform Destroy"
  dependsOn: TerraformApply
  condition: succeeded()
  jobs:
  - deployment: Destroy
    displayName: "Manual Approval and Destroy"
    environment: destroy-approval-environment  # 💡 Create this environment manually too
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(terraformVersion)

          - task: AzureCLI@2
            displayName: "Terraform Init and Destroy"
            inputs:
              azureSubscription: 'TerraformServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(Build.SourcesDirectory)'
              inlineScript: |
                terraform init -input=false
                terraform destroy -input=false -auto-approve -var-file="terraform.tfvars"
